# SDDM config — copiado a /etc/sddm.conf.d/arch-setup.conf por 3-caelestia-setup.sh

[Theme]
Current=catppuccin-mocha

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Autologin]
# Para activar auto-login (sin pedir contraseña al arrancar):
# descomentar las dos líneas siguientes y poner tu usuario
# User=tuusuario
# Session=hyprland
